import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ImageA from '../public/12.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <div className='flex justify-between sm:flex-row flex-col container'>
            <div className='box1 bg-red-300 lg:w-[15%] sm:w-[20%]'>
              <p>Title 1</p>
              <ul>
                <li>Home 1</li>
                <li>Home 1</li>
                <li>Home 1</li>
                <li>Home 1</li>
              </ul>
            </div>
            <div className='box1 bg-zinc-300 lg:w-[15%] sm:w-[20%]'>
              <p>Title 1</p>
              <ul>
                <li>Home 1</li>
                <li>Home 1</li>
                <li>Home 1</li>
                <li>Home 1</li>
              </ul>
            </div>
            <div className='box1 lg:w-[30%] sm:w-[25%] bg-orange-300'>
              <p>Title 1</p>
              <ul>
                <li>Home 1</li>
                <li>Home 1</li>
                <li>Home 1</li>
                <li>Home 1</li>
              </ul>
            </div>
            <div className='box1 lg:w-[40%] sm:w-[35%] bg-green-300'>
              <p>Title 1</p>
              <p>
                In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before final copy is available.
              </p>
            </div>
          </div>
        </div>

        <div className='flex container lg:flex-nowrap flex-wrap gap-8 justify-center'>
          <div className='lg:w-[20%] sm:w-[30%] w-[45%]'>
            <Image src={ImageA} alt="hello" />
          </div>
          <div className='lg:w-[20%] sm:w-[30%] w-[45%]'>
            <Image src={ImageA} alt="hello" />
          </div>
          <div className='lg:w-[20%] sm:w-[30%] w-[45%]'>
            <Image src={ImageA} alt="hello" />
          </div>
          <div className='lg:w-[20%] sm:w-[30%] w-[45%]'>
            <Image src={ImageA} alt="hello" />
          </div>
          <div className='lg:w-[20%] sm:w-[30%] w-[45%]'>
            <Image src={ImageA} alt="hello" />
          </div>
        </div>
      </main>
    </div>
  )
}
